example:
  family:
    father:
      age: 32
      sex: male
      name: Lisi
    mother:
      age: 30
      sex: female
      name: ZhangMeili
    son:
      age: 5
      sex: male
      name: LiDachui
